spring:
  application:
    name: inspire-web

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka


logging:
  path: E:\logs\inspire-web #打印存放日志的路径
  level:
    com.inspire: info #包名下日志的级别