server:
  port: 8762
eureka:
  client:
    #表明自己属于服务中心主体
    registerWithEureka: false #是否将自身注册
    fetchRegistry: false  #表示自己就是服务注册中心，我的职责就是为父服务实例，并不需要去检索服务
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  server:
    enable-self-preservation: false
logging:
  path: E:\logs\inspire-eureka
  level:
    com.inspire: info